version: '3'
services:
  # postgres:
  #   image: postgres:15.1
  #   networks:
  #     - postgres
  #   env_file:
  #     - docker.env
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data/pgdata
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234rewq
      POSTGRES_DB: mei14
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - '5431:5432'
    networks:
      - postgres

  redis:
    image: 'redis:alpine'
    networks:
      - postgres

  mei-ec:
    build:
      context: .
      dockerfile: Dockerfile
    image: mei-ec:latest
    env_file: docker.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
